# Generated by Django 3.2.8 on 2022-02-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_bids_value_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_bid',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bids',
            name='value_offer',
            field=models.FloatField(null=True),
        ),
    ]
