# Generated by Django 3.2.8 on 2022-02-14 01:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20220212_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist_list',
            field=models.ManyToManyField(null=True, related_name='watchlist_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
